//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.23 at 01:58:50 PM ICT 
//


package ABBYY;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * An ellipse shape. HPOS and VPOS describe the center of the ellipse.
 *                                 HLENGTH and VLENGTH are the width and height of the described ellipse.
 * 
 * <p>Java class for EllipseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EllipseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="HPOS" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="VPOS" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="HLENGTH" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="VLENGTH" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EllipseType", namespace = "http://www.loc.gov/standards/alto/ns-v3#")
public class EllipseType {

    @XmlAttribute(name = "HPOS", required = true)
    protected float hpos;
    @XmlAttribute(name = "VPOS", required = true)
    protected float vpos;
    @XmlAttribute(name = "HLENGTH", required = true)
    protected float hlength;
    @XmlAttribute(name = "VLENGTH", required = true)
    protected float vlength;

    /**
     * Gets the value of the hpos property.
     * 
     */
    public float getHPOS() {
        return hpos;
    }

    /**
     * Sets the value of the hpos property.
     * 
     */
    public void setHPOS(float value) {
        this.hpos = value;
    }

    /**
     * Gets the value of the vpos property.
     * 
     */
    public float getVPOS() {
        return vpos;
    }

    /**
     * Sets the value of the vpos property.
     * 
     */
    public void setVPOS(float value) {
        this.vpos = value;
    }

    /**
     * Gets the value of the hlength property.
     * 
     */
    public float getHLENGTH() {
        return hlength;
    }

    /**
     * Sets the value of the hlength property.
     * 
     */
    public void setHLENGTH(float value) {
        this.hlength = value;
    }

    /**
     * Gets the value of the vlength property.
     * 
     */
    public float getVLENGTH() {
        return vlength;
    }

    /**
     * Sets the value of the vlength property.
     * 
     */
    public void setVLENGTH(float value) {
        this.vlength = value;
    }

}
